mjenica/Areas/admin/Controllers/AdminPageController.cs
using mjenica.Areas.admin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mjenica.Areas.admin.Controllers
{
    [RouteArea("admin")]
    public class AdminPageController : ProtectedController
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

mjenica/Controllers/MjenicaController.cs
using mjenica.DAL;
using Spire.Doc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace mjenica.Controllers
{
    public class MjenicaController : Controller
    {
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NovaMjenica()
        {
            
            //FileStream fs = new FileStream(Server.MapPath(@"~\Sabloni\template1.rtf"), FileMode.Open, FileAccess.Read);
            //StreamReader sr = new StreamReader(fs);
            //string sve = sr.ReadToEnd();
            //sr.Close();
            //fs.Close();
            
            Document doc = new Document(Server.MapPath(@"~\Sabloni\template1.doc"));

            var sifra = KorisnikService.Instance.VratiSifruKorisnika(User.Identity.Name);
            doc.Replace("#s#", sifra, true, true);

            var zadnjiSerBroj = MjenicaService.Instance.VratiZadnjiSerijskiBroj();

            int br = int.Parse(zadnjiSerBroj);
            br++;

            var finalSerBroj = br.ToString("D8");

            doc.Replace("#serbroj#",finalSerBroj, true, true);
            doc.SaveToFile(Server.MapPath(@"~\Sabloni\template1_.pdf"), FileFormat.PDF);

            MemoryStream ms = new MemoryStream();
            doc.SaveToStream(ms, FileFormat.PDF);

            string mjenicaName = "mjenica-" + DateTime.Now.ToString().Trim().Replace(".", "").Replace("-", "").Replace("/", "").Replace(":", "").Trim() + ".pdf";

            FileContentResult fcr = new FileContentResult(ms.ToArray(), "application/pdf")
            {
                FileDownloadName = mjenicaName
            };

            ms.Close();

            var result = MjenicaService.Instance.DodajMjenicu(sifra, finalSerBroj);
            if (result.JeGreska)
                return View("Greska", result);

            return fcr;
        }
    }
}

mjenica/Controllers/RacuniController.cs
using Microsoft.Owin.Security;
using mjenica.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.DirectoryServices.AccountManagement;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace mjenica.Controllers
{
    public class RacuniController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginModel loginPodaci, string returnUrl)
        {
            if (!ModelState.IsValid)
                return View(this.Index());

            IAuthenticationManager iAuthManager = HttpContext.GetOwinContext().Authentication;

            PrincipalContext pc = new PrincipalContext(ContextType.Domain, "here-goes-domain-name");

            UserPrincipal up = UserPrincipal.FindByIdentity(pc, loginPodaci.KorisnickoIme);
            bool isSuccess = pc.ValidateCredentials(loginPodaci.KorisnickoIme, loginPodaci.Lozinka); // pogledati ContextOptions SSL ??

            if (!isSuccess)
                return View(this.Index());

            ClaimsIdentity ci = new ClaimsIdentity(MjenicaAuthType.AuthType, ClaimsIdentity.DefaultNameClaimType, ClaimsIdentity.DefaultRoleClaimType);
            ci.AddClaim(new Claim(ClaimTypes.Name, up.SamAccountName));
            ci.AddClaim(new Claim(ClaimTypes.NameIdentifier, up.SamAccountName));
            ci.AddClaim(new Claim("http://schemas.microsoft.com/accesscontrolservice/2010/07/claims/identityprovider", "active directory"));

            if (!string.IsNullOrEmpty(up.EmailAddress))
            {
                ci.AddClaim(new Claim(ClaimTypes.Email, up.EmailAddress));
            }

            foreach (var gr in up.GetAuthorizationGroups())
            {
                ci.AddClaim(new Claim(ClaimTypes.Role, gr.Name));
            }

            iAuthManager.SignOut(MjenicaAuthType.AuthType);
            iAuthManager.SignIn(new AuthenticationProperties() { IsPersistent = true }, ci);
            
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }

            return RedirectToAction("Index", "Naslovna");
        }

        private int VratiSifruKS(string korisnickoIme)
        {
            int sifra = -1;
            string confString = ConfigurationManager.ConnectionStrings["MjeniceDb"].ConnectionString;
            using (SqlConnection cn = new SqlConnection(confString))
            {
                cn.Open();

                SqlCommand cmd = new SqlCommand("SELECT UserID FROM KS_Sifre WHERE Username = '" + korisnickoIme + "'", cn);

                SqlDataReader dr = cmd.ExecuteReader();

                if (dr.HasRows)
                {
                    sifra = int.Parse(dr["UserID"].ToString());
                }

                dr.Close();
            }

            return sifra;
        }

        public ActionResult Logout()
        {
            IAuthenticationManager authManager = HttpContext.GetOwinContext().Authentication;
            authManager.SignOut(MjenicaAuthType.AuthType);

            return RedirectToAction("Index", "Naslovna");
        }
        
    }
}

mjenica/Views/Shared/Greska.cshtml
@model mjenica.Areas.admin.Models.ModelStatus

@{
    ViewBag.Title = "Greska";
    Layout = "~/Shared/_Layout.cshtml";
}

<h2>Greska</h2>

<div>
    <h4>Status greske:</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Detalji:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Opis)
        </dd>

    </dl>
</div>

mjenica/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Naslovna", "Index", "Naslovna")</li>
                    @if (Request.IsAuthenticated && User.IsInRole("Administrators")) {
                        <li>@Html.ActionLink("Admin", "Index", "AdminPage", new { area = "admin" }, null)</li>
                    }
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Mjenice", "Index", "Mjenica")</li>
                    }

                </ul>
                @if (Request.IsAuthenticated)
                {
                    <p class="nav navbar-text navbar-right">Prijavljeni ste kao: <i>@User.Identity.Name</i> | @Html.ActionLink("Odjavite se!", "Logout", "Racuni")</p>
                }
                else
                {
                    <p class="nav navbar-text navbar-right">@Html.ActionLink("Prijavite se!", "Index", "Racuni")</p>
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MKF MIKRO ALDI</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>